# https://github.com/tmux-plugins/tpm
- name: Install tmux plugin manager
  hosts: localhost

  tasks:
    - name: Clone tpm repository
      git:
        repo: https://github.com/tmux-plugins/tpm 
        dest: /home/fszuberski/.config/tmux/plugins/tpm
      when: ansible_distribution == "Archlinux"

    - name: Clone tpm repository (MacOSX)
      git:
        repo: https://github.com/tmux-plugins/tpm 
        dest: /Users/fszuberski/.config/tmux/plugins/tpm
      when: ansible_distribution == "MacOSX"
